services:
  springboot-app:
    image: my-spring-boot-app  # Spring Boot 애플리케이션 Docker 이미지 (빌드 필요)
    container_name: spring-boot-app
    ports:
      - "8082:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
